# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:10:29+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Query
from starlette.requests import Request

from models import Feedback, SeldonMessage, SeldonMessageList

app = MCPProxy(
    contact={'name': 'Seldon Core', 'url': 'https://github.com/SeldonIO/seldon-core'},
    title='Seldon External API',
    version='0.1',
    servers=[
        {'url': 'http://seldon.local'},
        {
            'url': 'http://{host}:{port}',
            'variables': {
                'host': {
                    'default': 'localhost',
                    'description': 'host running seldon core',
                },
                'port': {'default': '80'},
            },
        },
        {
            'description': 'fixed host as swagger UI has bug with variables for auth',
            'url': 'http://localhost:8002',
        },
    ],
)


@app.get('/aggregate', tags=['routing_logic'])
def aggregate(body: SeldonMessageList):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/aggregate', tags=['routing_logic'])
def aggregate2(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/predict', tags=['input_transformation', 'routing_logic'])
def transform_input4(json_: SeldonMessage = Query(..., alias='json')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/predict', tags=['routing_logic'])
def transform_input3(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/route', tags=['routing_logic'])
def route2(json_: SeldonMessage = Query(..., alias='json')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/route', tags=['routing_logic'])
def route(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/send-feedback', tags=['user_feedback_handling'])
def send_feedback2(json_: Feedback = Query(..., alias='json')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/send-feedback', tags=['routing_logic'])
def send_feedback(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/transform-input', tags=['input_transformation', 'routing_logic'])
def transform_input2(json_: SeldonMessage = Query(..., alias='json')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/transform-input', tags=['routing_logic'])
def transform_input(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/transform-output', tags=['routing_logic'])
def transform_output2(json_: SeldonMessage = Query(..., alias='json')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/transform-output', tags=['routing_logic'])
def transform_output(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
