# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:10:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class AnyValue(RootModel[Any]):
    root: Any = Field(
        ..., description='Can be anything: string, number, array, object, etc.'
    )


class MetricType(Enum):
    COUNTER = 'COUNTER'
    GAUGE = 'GAUGE'
    TIMER = 'TIMER'


class StatusStatusFlag(Enum):
    SUCCESS = 'SUCCESS'
    FAILURE = 'FAILURE'


class Tensor(BaseModel):
    shape: Optional[List[int]] = None
    values: Optional[List[float]] = None


class TensorShapeProtoDim(BaseModel):
    name: Optional[str] = Field(
        None, description='Optional name of the tensor dimension.'
    )
    size: Optional[str] = Field(
        None,
        description='Size of the tensor in that dimension.\nThis value must be >= -1, but values of -1 are reserved for "unknown"\nshapes (values of -1 mean "unknown" dimension).  Certain wrappers\nthat work with TensorShapeProto may fail at runtime when deserializing\na TensorShapeProto containing a dim value of -1.',
    )


class TensorflowDataType(Enum):
    DT_INVALID = 'DT_INVALID'
    DT_FLOAT = 'DT_FLOAT'
    DT_DOUBLE = 'DT_DOUBLE'
    DT_INT32 = 'DT_INT32'
    DT_UINT8 = 'DT_UINT8'
    DT_INT16 = 'DT_INT16'
    DT_INT8 = 'DT_INT8'
    DT_STRING = 'DT_STRING'
    DT_COMPLEX64 = 'DT_COMPLEX64'
    DT_INT64 = 'DT_INT64'
    DT_BOOL = 'DT_BOOL'
    DT_QINT8 = 'DT_QINT8'
    DT_QUINT8 = 'DT_QUINT8'
    DT_QINT32 = 'DT_QINT32'
    DT_BFLOAT16 = 'DT_BFLOAT16'
    DT_QINT16 = 'DT_QINT16'
    DT_QUINT16 = 'DT_QUINT16'
    DT_UINT16 = 'DT_UINT16'
    DT_COMPLEX128 = 'DT_COMPLEX128'
    DT_HALF = 'DT_HALF'
    DT_RESOURCE = 'DT_RESOURCE'
    DT_VARIANT = 'DT_VARIANT'
    DT_UINT32 = 'DT_UINT32'
    DT_UINT64 = 'DT_UINT64'
    DT_FLOAT_REF = 'DT_FLOAT_REF'
    DT_DOUBLE_REF = 'DT_DOUBLE_REF'
    DT_INT32_REF = 'DT_INT32_REF'
    DT_UINT8_REF = 'DT_UINT8_REF'
    DT_INT16_REF = 'DT_INT16_REF'
    DT_INT8_REF = 'DT_INT8_REF'
    DT_STRING_REF = 'DT_STRING_REF'
    DT_COMPLEX64_REF = 'DT_COMPLEX64_REF'
    DT_INT64_REF = 'DT_INT64_REF'
    DT_BOOL_REF = 'DT_BOOL_REF'
    DT_QINT8_REF = 'DT_QINT8_REF'
    DT_QUINT8_REF = 'DT_QUINT8_REF'
    DT_QINT32_REF = 'DT_QINT32_REF'
    DT_BFLOAT16_REF = 'DT_BFLOAT16_REF'
    DT_QINT16_REF = 'DT_QINT16_REF'
    DT_QUINT16_REF = 'DT_QUINT16_REF'
    DT_UINT16_REF = 'DT_UINT16_REF'
    DT_COMPLEX128_REF = 'DT_COMPLEX128_REF'
    DT_HALF_REF = 'DT_HALF_REF'
    DT_RESOURCE_REF = 'DT_RESOURCE_REF'
    DT_VARIANT_REF = 'DT_VARIANT_REF'
    DT_UINT32_REF = 'DT_UINT32_REF'
    DT_UINT64_REF = 'DT_UINT64_REF'


class TensorflowResourceHandleProto(BaseModel):
    container: Optional[str] = Field(
        None, description='Container in which this resource is placed.'
    )
    device: Optional[str] = Field(
        None, description='Unique name for the device containing the resource.'
    )
    hash_code: Optional[str] = Field(
        None,
        description='Hash code for the type of the resource. Is only valid in the same device\nand in the same execution.',
    )
    maybe_type_name: Optional[str] = Field(
        None,
        description='For debug-only, the name of the type pointed to by this handle, if\navailable.',
    )
    name: Optional[str] = Field(None, description='Unique name of this resource.')


class TensorflowTensorShapeProto(BaseModel):
    dim: Optional[List[TensorShapeProtoDim]] = Field(
        None,
        description='Dimensions of the tensor, such as {"input", 30}, {"output", 40}\nfor a 30 x 40 2D tensor.  If an entry has size -1, this\ncorresponds to a dimension of unknown size. The names are\noptional.\n\nThe order of entries in "dim" matters: It indicates the layout of the\nvalues in the tensor in-memory representation.\n\nThe first entry in "dim" is the outermost dimension used to layout the\nvalues, the last entry is the innermost dimension.  This matches the\nin-memory layout of RowMajor Eigen tensors.\n\nIf "dim.size()" > 0, "unknown_rank" must be false.',
    )
    unknown_rank: Optional[bool] = Field(
        None,
        description='If true, the number of dimensions in the shape is unknown.\n\nIf true, "dim.size()" must be 0.',
    )


class Metric(BaseModel):
    key: Optional[str] = None
    type: Optional[MetricType] = 'COUNTER'
    value: Optional[float] = None


class Status(BaseModel):
    code: Optional[int] = None
    info: Optional[str] = None
    reason: Optional[str] = None
    status: Optional[StatusStatusFlag] = 'SUCCESS'


class Meta(BaseModel):
    metrics: Optional[List[Metric]] = None
    puid: Optional[str] = None
    requestPath: Optional[Dict[str, str]] = Field(
        None, examples=[{'classifier': 'seldonio/mock_classifier:1.0'}]
    )
    routing: Optional[Dict[str, int]] = Field(None, examples=[{'router1': 1}])
    tags: Optional[Dict[str, AnyValue]] = Field(None, examples=[{'mytag': 'myvalue'}])


class DefaultData(BaseModel):
    names: Optional[List[str]] = None
    ndarry: Optional[List[AnyValue]] = None
    tensor: Optional[Tensor] = None
    tftensor: Optional[TensorflowTensorProto] = None


class Feedback(BaseModel):
    request: Optional[SeldonMessage] = None
    response: Optional[SeldonMessage] = None
    reward: Optional[float] = None
    truth: Optional[SeldonMessage] = None


class SeldonMessage(BaseModel):
    binData: Optional[str] = None
    data: Optional[DefaultData] = None
    meta: Optional[Meta] = None
    status: Optional[Status] = None
    strData: Optional[str] = None


class SeldonMessageList(BaseModel):
    seldonMessages: Optional[List[SeldonMessage]] = None


class TensorflowTensorProto(BaseModel):
    bool_val: Optional[List[bool]] = Field(None, title='DT_BOOL')
    dcomplex_val: Optional[List[float]] = Field(
        None,
        description='DT_COMPLEX128. dcomplex_val(2*i) and dcomplex_val(2*i+1) are real\nand imaginary parts of i-th double precision complex.',
    )
    double_val: Optional[List[float]] = Field(None, description='DT_DOUBLE.')
    dtype: Optional[TensorflowDataType] = 'DT_INVALID'
    float_val: Optional[List[float]] = Field(None, description='DT_FLOAT.')
    half_val: Optional[List[int]] = Field(
        None,
        description="DT_HALF, DT_BFLOAT16. Note that since protobuf has no int16 type, we'll\nhave some pointless zero padding for each value here.",
    )
    int64_val: Optional[List[str]] = Field(None, title='DT_INT64')
    int_val: Optional[List[int]] = Field(
        None, description='DT_INT32, DT_INT16, DT_INT8, DT_UINT8.'
    )
    resource_handle_val: Optional[List[TensorflowResourceHandleProto]] = Field(
        None, title='DT_RESOURCE'
    )
    scomplex_val: Optional[List[float]] = Field(
        None,
        description='DT_COMPLEX64. scomplex_val(2*i) and scomplex_val(2*i+1) are real\nand imaginary parts of i-th single precision complex.',
    )
    string_val: Optional[List[str]] = Field(None, title='DT_STRING')
    tensor_content: Optional[str] = Field(
        None,
        description='Serialized raw tensor content from either Tensor::AsProtoTensorContent or\nmemcpy in tensorflow::grpc::EncodeTensorToByteBuffer. This representation\ncan be used for all tensor types. The purpose of this representation is to\nreduce serialization overhead during RPC call by avoiding serialization of\nmany repeated small items.',
    )
    tensor_shape: Optional[TensorflowTensorShapeProto] = Field(
        None,
        description='Shape of the tensor.  TODO(touts): sort out the 0-rank issues.',
    )
    uint32_val: Optional[List[int]] = Field(None, title='DT_UINT32')
    uint64_val: Optional[List[str]] = Field(None, title='DT_UINT64')
    variant_val: Optional[List[TensorflowVariantTensorDataProto]] = Field(
        None, title='DT_VARIANT'
    )
    version_number: Optional[int] = Field(
        None,
        description='Version number.\n\nIn version 0, if the "repeated xxx" representations contain only one\nelement, that element is repeated to fill the shape.  This makes it easy\nto represent a constant Tensor with a single value.',
    )


class TensorflowVariantTensorDataProto(BaseModel):
    metadata: Optional[str] = Field(
        None, description='Portions of the object that are not Tensors.'
    )
    tensors: Optional[List[TensorflowTensorProto]] = Field(
        None, description='Tensors contained within objects being serialized.'
    )
    type_name: Optional[str] = Field(
        None, description='Name of the type of objects being serialized.'
    )


class AggregatePostRequest(BaseModel):
    json_: Optional[SeldonMessageList] = Field(None, alias='json')


class PredictPostRequest(BaseModel):
    json_: Optional[SeldonMessage] = Field(None, alias='json')


class RoutePostRequest(BaseModel):
    json_: Optional[SeldonMessage] = Field(None, alias='json')


class SendFeedbackPostRequest(BaseModel):
    json_: Optional[Feedback] = Field(None, alias='json')


class TransformInputPostRequest(BaseModel):
    json_: Optional[SeldonMessage] = Field(None, alias='json')


class TransformOutputPostRequest(BaseModel):
    json_: Optional[SeldonMessage] = Field(None, alias='json')


DefaultData.model_rebuild()
Feedback.model_rebuild()
TensorflowTensorProto.model_rebuild()
